# Simplified Cloud Build configuration (use this if the main one fails)
steps:
  # Build and push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/forecast-service:latest'
      - '.'
    timeout: '1200s'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/forecast-service:latest']
  
  # Deploy to Cloud Run (without env vars - set them separately)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'forecast-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/forecast-service:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/forecast-service:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

