steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/forecast-service:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/forecast-service:latest'
      - '.'
    timeout: '1200s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/forecast-service']
    waitFor: ['build-image']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-service'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'forecast-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/forecast-service:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID},TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN},TWILIO_WHATSAPP_FROM=${_TWILIO_WHATSAPP_FROM}'
    waitFor: ['push-image']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/forecast-service:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/forecast-service:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'

# Substitution variables (set these in Cloud Build trigger settings)
substitutions:
  _REGION: 'us-central1'
  _TWILIO_ACCOUNT_SID: ''
  _TWILIO_AUTH_TOKEN: ''
  _TWILIO_WHATSAPP_FROM: ''

timeout: '1800s'

